---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-sert2521-deployment
  namespace: sert2521
  labels:
    app: sert2521
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sert2521
  template:
    metadata:
      labels:
        app: sert2521
    spec:
      containers:
        - name: web-server
          image: mvpstudio/sert2521:76f0035
          resources:
            limits:
              cpu: 0.25
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: sert2521-mysql
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sert2521-mysql-credentials
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sert2521-mysql-credentials
                  key: password
            - name: DATABASE_NAME
              value: sert2521-default
            - name: DATABASE_PORT
              value: "3306"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: sert2521-web
  namespace: sert2521
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: sert2521-mapping
      host: sert2521.stage.apps.mvpstudio.org
      prefix: /
      service: sert2521-web.sert2521
      timeout_ms: 20000
      ---
      apiVersion: ambassador/v0
      kind: TLSContext
      name: stage-sert2521-tls
      hosts:
      - sert2521.stage.apps.mvpstudio.org
      secret: stage-apps-cert
spec:
  selector:
    app: sert2521
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sert2521-mysql
  namespace: sert2521
  labels:
    app: sert2521-mysql
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: sert2521-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stage-sert2521-mysql-deploy
  namespace: sert2521
spec:
  serviceName: sert2521-mysql
  selector:
    matchLabels:
      app: sert2521-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: sert2521-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sert2521-mysql-credentials
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: sert2521-mysql-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sert2521-mysql-credentials
                  key: password
            - name: MYSQL_DATABASE
              value: sert2521-default
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysqldata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
